apiVersion: v1
kind: Service
metadata:
  name: {{ include "notification-poc.serviceName" . }}
  labels:
    {{- include "notification-poc.labels" (dict "name" (include "notification-poc.serviceName" .) "context" $) | nindent 4 }}
spec:
  selector:
    {{- include "notification-poc.selectorLabels" (dict "name" (include "notification-poc.serviceName" .)) | nindent 4 }}
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
