apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-ev-worker-config
  labels:
    {{- include "notification-poc.labels" (dict "name" "notification-ev-worker" "context" $) | nindent 4 }}
data:
  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.kafka.bootstrapServers | quote }}
  KAFKA_CONSUMER_GROUP_ID: {{ .Values.evWorker.kafka.consumerGroup | quote }}
  KAFKA_CONSUMER_MODE: {{ .Values.evWorker.kafka.consumerMode | default "consumer-group" | quote }}
  TEMPORAL_ADDRESS: {{ .Values.temporal.address | quote }}
