apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-message-wf-worker-config
  labels:
    {{- include "notification-poc.labels" (dict "name" "notification-message-wf-worker" "context" $) | nindent 4 }}
data:
  TEMPORAL_ADDRESS: {{ .Values.temporal.address | quote }}
  SERVICES_BASE_URL: {{ include "notification-poc.serviceUrl" . | quote }}
