apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-wf-worker-config
  labels:
    {{- include "notification-poc.labels" (dict "name" "notification-wf-worker" "context" $) | nindent 4 }}
data:
  TEMPORAL_ADDRESS: {{ .Values.temporal.address | quote }}
  TEMPORAL_TASK_QUEUE: {{ .Values.temporal.taskQueue | default "NOTIFICATION_QUEUE" | quote }}
